// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/shield-128.png"
    | "/icon/shield-128.svg"
    | "/icon/shield-16.png"
    | "/icon/shield-16.svg"
    | "/icon/shield-32.png"
    | "/icon/shield-32.svg"
    | "/icon/shield-48.png"
    | "/icon/shield-48.svg"
    | "/icon/shield-ghost.png"
    | "/icon/shield-ghost.svg"
    | "/icon/shield-guardian.png"
    | "/icon/shield-guardian.svg"
    | "/icon/shield-sentry.png"
    | "/icon/shield-sentry.svg"
    | "/icon/shield.svg"
    | "/options.html"
    | "/popup.html"
    | "/rules/ai_chat_widgets.json"
    | "/rules/ai_content_injectors.json"
    | "/rules/ai_popups.json"
    | "/rules/ai_search_overlays.json"
    | "/rules/ai_social_features.json"
    | "/rules/ai_trackers.json"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
